export const errorDefinitions = {
    "B@BCNS": "Engine Overheat",
    "B@BAZG": "Engine Oil Press. Low",
    "CA111": "ECM Critical Internal Failure",
    "CA115": "Eng. Ne and Backup Speed Sensor Error",
    "CA122": "Charge Air Press Sensor High Error",
    "CA123": "Charge Air Press Sensor Low Error",
    "CA131": "Throttle Sensor High Error",
    "CA132": "Throttle Sensor Low Error",
    "CA187": "Sensor Sup. 2 Volt Low Error",
    "CA227": "Sensor Sup. 2 Volt High Error",
    "CA234": "Eng. Overspeed",
    "CA238": "Ne Speed Sensor Sup. Volt. Error",
    "CA271": "IMV/PCV1 Short Error",
    "CA272": "IMV/PCV1 Open Error",
    "CA273": "PCV2 Short Error",
    "CA274": "PCV2 Open Error",
    "CA322": "Injector #1 (L/B #1) Open/Short Error",
    "CA323": "Injector #5 (L/B #5) Open/Short Error",
    "CA324": "Injector #3 (L/B #3) Open/Short Error",
    "CA325": "Injector #6 (L/B #6) Open/Short Error",
    "CA331": "Injector #2 (L/B #2) Open/Short Error",
    "CA332": "Injector #4 (L/B #4) Open/Short Error",
    "CA342": "Calibration Code Incompatibility",
    "CA351": "INJ. Drive Circuit Error",
    "CA352": "Sensor Sup. 1 Volt. Low Error",
    "CA386": "Sensor Sup. 1 Volt. High Error",
    "CA432": "Idle Validation Process Error",
    "CA441": "Battery Voltage Low Error",
    "CA442": "Battery Voltage High Error",
    "CA449": "Rail Press. Very High Error",
    "CA451": "Rail Press. Sensor High Error",
    "CA452": "Rail Press. Sensor Low Error",
    "CA553": "Rail Press. High Error",
    "CA554": "Rail Press. Sensor In Range Error",
    "CA559": "Rail Press. Low Error",
    "CA689": "Eng. Ne Speed Sensor Error",
    "CA697": "ECM Int. Temp. Sensor High Error",
    "CA698": "ECM Int. Temp. Low Volt. Error",
    "CA731": "Eng. Backup Speed Sensor Phase Error",
    "CA757": "All Persistent Data Lost Error",
}